name: Publish

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - run: make wagon.archive
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: make wagon.ship
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            build/output/*.tar.gz
